"""full_name not unique

Revision ID: 9e2f204b9368
Revises: 17cb66d93d8a
Create Date: 2024-01-20 14:33:17.178058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2f204b9368'
down_revision: Union[str, None] = '17cb66d93d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_full_name_key', 'urls', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('urls_full_name_key', 'urls', ['full_name'])
    # ### end Alembic commands ###
