"""Add created_at field to urls

Revision ID: d5ebcc8bff4f
Revises: 9e2f204b9368
Create Date: 2024-01-20 14:43:41.661442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ebcc8bff4f'
down_revision: Union[str, None] = '9e2f204b9368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'created_at')
    # ### end Alembic commands ###
